version: "3.3"

services:
  rest-api-postgresql:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    volumes:
      - viban-pgdata:/var/lib/postgresql/data

volumes:
  viban-pgdata:
